-- EXECUTE THE ADD CUSTOMER PROCEDURE

EXECUTE BANK_PACKAGE.PROC_ADD_CUSTOMER('JAMES','S','MILLER','M','01-JUN-2018','IND');
SELECT * FROM BANK_CUST;

-- EXECUTE THE PRO_ADD_CUST_CONTACT PROCEDURE

EXECUTE BANK_PACKAGE.PROC_ADD_CUST_CONTACT(1011,9885000935,'HOME','56 RD NO 14 B HILLS','BNR COLONY','HYD','TS',500034);
SELECT * FROM BANK_CUST_CONTACT;

-- EXECUTE THE PRO_ADD_SB_ACCOUNT PROCEDURE

EXECUTE BANK_PACKAGE.PROC_ADD_SB_ACCOUNT(1011,NULL,1000,'ACTIVE',SYSDATE,NULL);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

-- EXECUTE THE PR_SB_DEPOSIT PROCEDURE

EXECUTE BANK_PACKAGE.PROC_SB_DEPOSIT (1000012011,'Deposit',1000);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

-- EXECUTE THE PR_SB_DEPOSIT WITHDRAW PROCEDURE

EXECUTE BANK_PACKAGE.PROC_SB_WITHDRAW(1000012011,'Withdrawal',1000);
SELECT * FROM BANK_SB_ACCOUNT;
SELECT * FROM BANK_TRANSACTION;

